Add Bottle Technology Pvt. Ltd
developers-nepal/tech-companies-in-nepal pull request #7
Opened 2021-10-10 14:02 UTC by sidbelbase

Hi, I added Bottle Technology Pvt. Ltd. which lies in Lalitpur in this pull request & also can you add the label `hacktoberfest` or `hacktoberfest-accepted` to this pull request (either is fine) so that it can count towards my Hacktoberfest objective?

Many thanks :)

2021-10-11 01:30 UTC, techgaun requested changes

2021-10-11 01:30 UTC, techgaun commented on README.md
> +- [Bottle Technology](https://bottle.com.np/) | Jamshikhel, Lalitpur | Bottle is a fintech company mostly specializing in the space of Artificial Intelligence, Behavioral Economics and Internet of Th
```suggestion
- [Bottle Technology](https://bottle.com.np/) | Jhamshikhel, Lalitpur | A fintech company mostly specializing in the space of Artificial Intelligence, Behavioral Economics and Internet of Things.
```
I would make it more concise also, is it Jhamsikhel or Jamshikhel?

2021-10-25 13:03 UTC, sarojbelbase commented
Hi, I have added new changes that you added. Please check back again.

2021-10-25 16:25 UTC, techgaun approved these changes

2021-10-25 16:25 UTC, merged