Update README.md
developers-nepal/tech-companies-in-nepal pull request #8
Opened 2022-03-31 14:35 UTC by NiranjanNlc

Adding Sherpa tech information

2022-03-31 17:46 UTC, techgaun requested changes
The URL does not seem like working, sounds like `www` is the culprit there. https://sherpa-tech.com/ seems to work though

2022-04-01 01:27 UTC, NiranjanNlc reviewed
Updated by removing www

2022-04-01 05:09 UTC, techgaun requested changes

2022-04-01 05:09 UTC, techgaun commented on README.md
> +- [Sherpa Tech](https://sherpa-tech.com/) |Jamal , Kathmandu |Software, Web development and Consulting company  since 2010.
```suggestion
- [Sherpa Tech](https://sherpa-tech.com/) | Jamal , Kathmandu | Software, Web development and Consulting company since 2010.
```

2022-04-02 21:44 UTC, techgaun approved these changes

2022-04-02 21:44 UTC, merged